# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:
    deps:
      - clean
    cmds:
      - go build -o ./bin/subtitles .
    silent: true
  clean:
    cmds:
      - rm -rf ./bin
    silent: true
