# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:
    deps:
      - clean
    cmds:
      - go build -o ./bin/subtitles .
    silent: true
  clean:
    cmds:
      - rm -rf ./bin
    silent: true
  test:
    cmds:
      - go test -v ./...
    silent: true
  dog-park:
      cmds:
        - ./bin/subtitles translate:all -s en "$HOME/Movies/First Fourteen Minutes_iTT_English.srt.vtt"
